[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8502
address = "0.0.0.0"
[theme] #
primaryColor = '#FF8C02' # Bright Orange
backgroundColor = '#00325B' # Dark Blue
secondaryBackgroundColor = '#55B2FF' # Lighter Blue
[browser]
gatherUsageStats = true
